language: c
os:
    - linux
    - osx
compiler:
    - clang
    - gcc

before_install:
    - if [ `uname` == "Linux" ]; then sudo apt-get update -qq && sudo apt-get install -qq check zlib1g-dev; fi
    - if [ `uname` == "Darwin" ]; then brew update && brew install check; fi

script: make && make test

install: true
